install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  include:
    - script: l3build check -q -H --show-log-on-error
      name: "Test suite"
    - script: l3build doc -q -H --show-log-on-error
      name: "Documentation"

notifications:
  email:
    recipients:
      - latex3-commits@tug.org
    on_success: change
    on_failure: always
    on_start:   never

