before_install:
 - sudo apt-get install ghostscript

install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

jobs:
  include:
    - if: NOT tag IS present
      script: l3build check -q -H --show-log-on-error
      name: "Test suite"
    - if: NOT tag IS present
      script: l3build doc -q -H --show-log-on-error
      name: "Documentation"
    - if: tag IS present
      script: l3build ctan -H --show-log-on-error
      name: "Full CTAN build"

notifications:
  email:
    recipients:
      - latex3-commits@tug.org
    on_success: change
    on_failure: always
    on_start:   never

deploy:
  - provider: releases
    api_key:
      secure: "aDWsie9RzVVvI5CE9qIxid23bQr6VVSzMKHIqDCByux1ZBlwrNwcUsoStWYlejRqj1qgrsQpHaMSgwFx4lr+Lclqf5jYPWXpK1A88/btFVRmni4Fpur95zhu4Hs+0D+w0wyuWU1SqhC+pQ8ix8+Blj44j3+LbSHfVFAQoph6j0FJLYH77jcrbd13ALkVeYbZH29HefH2suDClNgBb1LbNPdUhERVXhYR7y5Ci4Rd89HwrSb7cjJL72nDOUfMaZPyCLhbFImMwWuFLN2+0UlM0jIyiL/9Wta3k/m2DfllROD/U6s9eRhCKoEkX4m0Tm7Fa87g3/J0N3Bg1wVSEnZG3gVUL3WHALWbIIwlx8l2LJyKs2elt07oZ63YFo0RYyYGgaNA3/xpcB9btAuSo0CNhz9NydkuPKX/RFM8ttlHMGbXzUahd+nMI+OQZ7Fy9AAlPTJgZ4CoAmt0ros02pHMdxJNBXqzgitxzmv7m/Ka+OVDTM49hqenBFb7JELLwYMoMxThV39kLGCDxmsHzKruqfe6/r6vqZy/XDnsZoUUEBK6qsME30CmTDR0NfKsmJAxAIJz8oVm/GSTr7yaB8ZNsBYl2kmpFmYGOA6GTRZz7MceTAetTuKALgc4Tv/4tCw5pF4cXlZavK+7n4fzmZhm746hvjnZqC+5noFj0wQWnfw="
    file_glob: true
    file:
      - ./*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG == *-dev
    prerelease: true
  - provider: releases
    api_key:
      secure: "aDWsie9RzVVvI5CE9qIxid23bQr6VVSzMKHIqDCByux1ZBlwrNwcUsoStWYlejRqj1qgrsQpHaMSgwFx4lr+Lclqf5jYPWXpK1A88/btFVRmni4Fpur95zhu4Hs+0D+w0wyuWU1SqhC+pQ8ix8+Blj44j3+LbSHfVFAQoph6j0FJLYH77jcrbd13ALkVeYbZH29HefH2suDClNgBb1LbNPdUhERVXhYR7y5Ci4Rd89HwrSb7cjJL72nDOUfMaZPyCLhbFImMwWuFLN2+0UlM0jIyiL/9Wta3k/m2DfllROD/U6s9eRhCKoEkX4m0Tm7Fa87g3/J0N3Bg1wVSEnZG3gVUL3WHALWbIIwlx8l2LJyKs2elt07oZ63YFo0RYyYGgaNA3/xpcB9btAuSo0CNhz9NydkuPKX/RFM8ttlHMGbXzUahd+nMI+OQZ7Fy9AAlPTJgZ4CoAmt0ros02pHMdxJNBXqzgitxzmv7m/Ka+OVDTM49hqenBFb7JELLwYMoMxThV39kLGCDxmsHzKruqfe6/r6vqZy/XDnsZoUUEBK6qsME30CmTDR0NfKsmJAxAIJz8oVm/GSTr7yaB8ZNsBYl2kmpFmYGOA6GTRZz7MceTAetTuKALgc4Tv/4tCw5pF4cXlZavK+7n4fzmZhm746hvjnZqC+5noFj0wQWnfw="
    file_glob: true
    file:
      - ./*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG != *-dev
    prerelease: false