name: Automated testing

# Currently we run in two situations:
on:
  # Whenever someone pushes to a branch in our repo
  push:
    branches:
      - "*"
  # Whenever a pull request is opened, reopened or gets new commits.
  pull_request:
# This implies that for every push to a local branch in our repo for which a
# pull request is open this runs twice. But it's important to ensure that pull
# requests get tested even if their branch comes from a fork.

jobs:
  # Update the TeX Live tree if necessary
  texlive-cache:
    runs-on: ubuntu-20.04
    name: Update TeX Live
    outputs:
      cache_key: ${{ steps.texlive.outputs.cache_key }}
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install TeX Live
        id: texlive
        uses: zauguin/install-texlive@v3
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
  # The l3build job contains the actual work. We misuse the matrix mechanism to
  # create three jobs which only differ in minimal elements.
  # For tags we do not run this since we run the release job instead.
  l3build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # include indicates that we want to set explicitly these combinations
        # and don't want full matrix testing.
        # "name" is just to make the output more readable.
        # "l3build_cmd" is the actual command to run
        # "artifact_name" is which artifact might get generated by this step.
        # IMPORTANT: artifact_name == "Documentation" is used as a trigger to
        # generate the artifact from PDF files and not the build directory and
        # to generate the artifact when the run is successful, not when it fails.
        include:
          - name: "Tests: base - build - pdftex"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c build -e pdftex
            artifact_name: testfiles
          - name: "Tests: base - build - xetex"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c build -e xetex
            artifact_name: testfiles
          - name: "Tests: base - build - luatex"
            l3build_cmd: cd base && kpsewhich -mktex=tfm -must-exist ecssdc10.tfm && l3build check -q --show-log-on-error -c build -e luatex
            artifact_name: testfiles
          - name: "Tests: base - 1run"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-1run
            artifact_name: testfiles
          - name: "Tests: base - TU"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-TU
            artifact_name: testfiles
          - name: "Tests: base - legacy"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-legacy
            artifact_name: testfiles
          - name: "Tests: base - lthooks"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-lthooks
            artifact_name: testfiles
          - name: "Tests: base - lthooks2"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-lthooks2
            artifact_name: testfiles
          - name: "Tests: base - ltcmd"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-ltcmd
            artifact_name: testfiles
          - name: "Tests: base - doc"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-doc
            artifact_name: testfiles
          - name: "Tests: base - ltmarks"
            l3build_cmd: cd base && l3build check -q --show-log-on-error -c config-ltmarks
            artifact_name: testfiles
          - name: "Tests: required"
            l3build_cmd: cd required && l3build check -q --show-log-on-error
            artifact_name: testfiles
          - name: "Documentation: base"
            l3build_cmd: cd base && l3build doc -q -H --show-log-on-error
            artifact_name: Documentation
          - name: "Documentation: required"
            l3build_cmd: cd required && l3build doc -q -H --show-log-on-error
            artifact_name: Documentation
    name: ${{ matrix.name }}
    needs: texlive-cache
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v3
      # We need Ghostscript for dvips and XeTeX tests.
      - run: sudo apt-get update && sudo apt-get install ghostscript
      - name: Restore TeX Live from cache
        uses: actions/cache/restore@v3
        with:
          path: ~/texlive
          key: ${{ needs.texlive-cache.outputs.cache_key }}
          fail-on-cache-miss: true
      - run: echo $HOME/texlive/bin/x86_64-linux >> $GITHUB_PATH
      - name: Run l3build
        run: ${{ matrix.l3build_cmd }}
      # Now we create the artifacts: There are two cases where this happens.
      # 1. If we failed running tests
      - name: Archive failed test output
        if: ${{ always() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          name: ${{ matrix.artifact_name }}
          # Decide how long to keep the test output artifact:
          retention-days: 3
      # 2. If we succeed building documentation
      - name: Archive documentation
        if: ${{ matrix.artifact_name == 'Documentation' && success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: "**/*.pdf"
          # Decide how long to keep the test output artifact:
          retention-days: 21
  # GitHub automatically informs the initiator of any action about the result, but
  # we additionally want to keep the latex-commits mailing list informed about
  # test failures.
  notifiy:
    name: Send notifications
    runs-on: ubuntu-20.04
    # Run after the `l3build` job in order to be able to react to it's output.
    needs: l3build
    # Only run if the tests failed, we don't want to get notifications for every run.
    # We don't want information for pull requests since for pull requests from local
    # branches we already send notifications when the branch test fails and pull requests
    # from forks can't access the username and password secrets required to send mails.
    if: ${{ failure() && github.event_name != 'pull_request' }}
    steps:
      - name: Send mail
        # The explicit commit hash ensures that this can't be used by dawidd6 as a
        # backdoor to execute arbitrary code during our runs.
        uses: dawidd6/action-send-mail@6063705cefe50cb915fc53bb06d4049cae2953b2
        with:
          # Currently using my (Marcel's) mail server for sending mails.
          server_address: typesetting.eu
          server_port: 587
          # These values can be changed in the repository settings.
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # If we want to send notifications to additional addresses, at them here as
          # a comma separated list.
          to: latex3-commits@tug.org
          # The name is arbitrary, but if you want to change the address you need to
          # coordinate it with the administrator of the mail server to allow the account
          # to send from the mail address.
          from: LaTeX CI <github@latex-project.org>
          priority: high
          # Determine the subject and body of the mail.
          subject: "Test failed: ${{github.repository}} (${{github.ref}})"
          body: |
            Test failure for ${{github.repository}}
            -------------------------------------------------------------

            On branch:        ${{github.ref}} (${{github.sha}})
            Initiated by:     ${{github.actor}}
            Commit URL:       https://github.com/${{github.repository}}/commit/${{github.sha}}
            More information: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
